storage: ../tmp/local-registry/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m
    max_fails: 20
    fail_timeout: 2m

packages:
  "@*/*":
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  "**":
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true # set offline to true to allow publish offline
