version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - "/packages/*"
      - "/tools/*"
    schedule:
      interval: weekly
    versioning-strategy: increase
    cooldown:
      semver-minor-days: 3
      semver-patch-days: 7
    groups:
      npm-security-patch-minor:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - patch
          - minor
      npm-runtime-patch:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - patch
      npm-dev-patch-minor:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - patch
          - minor
      npm-version-updates:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@the-stranger/*"
      - dependency-name: "@nx/*"
      - dependency-name: nx

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
