approvedGitRepositories:
  - "**"

cloneConcurrency: 8

enableGlobalCache: false

enableScripts: true

injectEnvironmentFiles:
  - .env?
  - .env.ci?
  - .env.dev?
  - .env.production?

nodeLinker: node-modules

preferReuse: true

tsEnableAutoTypes: true
