cloneConcurrency: 8

enableGlobalCache: false

injectEnvironmentFiles:
  - .env?
  - .env.ci?
  - .env.production?

nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  the-stranger:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}
    npmRegistryServer: https://registry.npmjs.org/

preferReuse: true

tsEnableAutoTypes: true
