version: "0.2"
language: en
import:
  - "@cspell/dict-fr-fr/cspell-ext.json"
  - "@cspell/dict-scientific-terms-us/cspell-ext.json"
ignorePaths:
  - .env*
  - .vscode
  - .yarnrc.yml
  - dist
  - env.d.ts
  - node_modules
  - yarn.lock
dictionaries:
  - companies
  - computing-acronyms
  - filetypes
  - fonts
  - fullstack
  - git
  - misc
  - networking-terms
  - npm
  - scientific-terms-us
  - softwareTerms
  - web-services
words:
  - globbify
  - lestranger
languageSettings:
  - languageId: javascript,typescript
    dictionaries:
      - node
      - npm
      - typescript
  - languageId: json,jsonc
    dictionaries:
      - node
      - npm
  - languageId: markdown
    dictionaries:
      - fr-fr
      - html
      - html-symbol-entities
      - latex
      - node
      - npm
