version: "0.2"
language: en
import:
  - ./node_modules/@cspell/dict-fr-fr/cspell-ext.json
  - ./node_modules/@cspell/dict-scientific-terms-us/cspell-ext.json
ignorePaths:
  - .cspellcache
  - .dcignore
  - .env*
  - .git
  - .gitattributes
  - .gitignore
  - .nx
  - .nxignore
  - .prettierignore
  - .verdaccio
  - .vscode
  - .yarnrc.yml
  - coverage
  - dist
  - env.d.ts
  - node_modules
  - out-tsc
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - tmp
  - yarn.lock
dictionaries:
  - companies
  - computing-acronyms
  - filetypes
  - fonts
  - fullstack
  - git
  - misc
  - networking-terms
  - npm
  - scientific-terms-us
  - softwareTerms
  - web-services
ignoreWords:
  - cipe
  - codexignore
  - dcignore
  - nxignore
words:
  - dotenvx
  - globbify
  - lestranger
  - orcid
  - unprefix
  - unstub
languageSettings:
  - languageId: javascript,typescript
    dictionaries:
      - node
      - npm
      - typescript
  - languageId: json,jsonc,yaml
    dictionaries:
      - node
      - npm
  - languageId: markdown
    dictionaries:
      - fr-fr
      - html
      - html-symbol-entities
      - latex
      - node
      - npm
