export { getProperty } from './get-property'
export { maybeParsePath, parsePath } from './parse-path'
export { PathParser } from './parser'
export { setProperty } from './set-property'
export type { PropertyPath, PropertyPathSegment } from './types'
