import type { Rules } from './rules.js'

export const sortRules = {
  'perfectionist/sort-classes': [
    'warn',
    {
      groups: [
        'static-property',
        'property',
        'protected-static-property',
        'protected-property',
        'private-static-property',
        'private-property',
        'constructor',
        'index-signature',
        'static-accessor-property',
        'accessor-property',
        ['static-method', 'static-function-property'],
        ['method', 'function-property'],
        ['static-get-method', 'static-set-method'],
        ['get-method', 'set-method'],
        'override-method',
        'static-block',
        ['protected-static-method', 'protected-static-function-property'],
        ['protected-method', 'protected-function-property'],
        ['private-static-method', 'private-static-function-property'],
        ['private-method', 'private-function-property'],
        'protected-static-accessor-property',
        'protected-accessor-property',
        'private-static-accessor-property',
        'private-accessor-property',
        ['protected-static-get-method', 'protected-static-set-method'],
        ['protected-get-method', 'protected-set-method'],
        ['private-static-get-method', 'private-static-set-method'],
        ['private-get-method', 'private-set-method'],
        'unknown',
      ],
    },
  ],
  'perfectionist/sort-enums': ['warn', { sortByValue: 'never' }],
  'perfectionist/sort-exports': 'warn',
  'perfectionist/sort-imports': [
    'warn',
    {
      groups: [
        ['side-effect', 'side-effect-style'],
        'style',
        'value-builtin',
        'value-external',
        'type-import',
        'type-internal',
        'value-internal',
        ['type-parent', 'type-sibling', 'type-index'],
        ['value-parent', 'value-sibling', 'value-index'],
        'ts-equals-import',
        'unknown',
      ],
    },
  ],
  'perfectionist/sort-interfaces': 'off',
  'perfectionist/sort-modules': [
    'warn',
    {
      groups: [
        'unknown',
        'export-class',
        'export-function',
        'export-enum',
        ['export-interface', 'export-type'],
        'class',
        'function',
        'enum',
        ['interface', 'type'],
        [
          'export-default-class',
          'export-default-function',
          'export-default-enum',
          'export-default-type',
          'export-default-interface',
        ],
      ],
    },
  ],
  'perfectionist/sort-named-exports': [
    'warn',
    { groups: ['value-export', 'type-export'] },
  ],
  'perfectionist/sort-named-imports': [
    'warn',
    { groups: ['type-import', 'value-import', 'unknown'] },
  ],
  'perfectionist/sort-union-types': [
    'warn',
    {
      groups: [
        'conditional',
        'function',
        'operator',
        'literal',
        'keyword',
        'named',
        'import',
        'tuple',
        'object',
        ['intersection', 'union'],
        'nullish',
        'unknown',
      ],
      ignoreCase: false,
      type: 'natural',
    },
  ],
} satisfies Rules
