export { addDependenciesToProject, getWorkspaceVersion } from './lib/add-dependencies'
export { markerFiles } from './lib/config-marker-files'
export { detectConfig, type ConfigTypes } from './lib/detect-config'
export { FileNotFoundError } from './lib/errors/file-not-found'
export { exists } from './lib/exists'
export { findExisting } from './lib/find-existing'
export { formatFiles } from './lib/format-files'
export type { GeneratorSchema } from './lib/generator-schema'
export { isEmpty } from './lib/is-empty'
export { maybeReadJson, readJson, writeJson, type WriteJsonOptions } from './lib/json'
export { owStrategy } from './lib/overwrite-strategy'
export { removeAll } from './lib/remove-all'
export { toArray } from './lib/to-array'
export { TSConfig, type TSConfigOptions } from './lib/tsconfig'
