name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_CI }}

jobs:
  ci:
    name: Run lint, unit tests, and validate build for Node.js
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: nrwl/nx-set-shas@v4
      - run: corepack enable && corepack install
      - uses: actions/setup-node@v5
        with:
          cache: yarn
          node-version: 24
      - name: install Node.js dependencies
        run: yarn install
      - name: lint, test, build
        run: yarn nx affected -t lint test build
