name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main

permissions:
  actions: read
  contents: read

jobs:
  ci:
    name: Run lint, unit tests, and validate build for Node.js
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ./.github/workflows/setup-node.yml
        with:
          set-nx-shas: true
      - name: install Node.js dependencies
        run: yarn install
      - name: lint, test, build
        run: yarn nx affected -t lint test build
