name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_CI }}

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: nrwl/nx-set-shas@v4
      - run: corepack enable && corepack install
      - uses: actions/setup-node@v5
        with:
          cache: yarn
          node-version: 24
      - run: yarn install
      - name: lint, test, build
        run: yarn nx run-many -t lint test build
