name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  build:
    name: Run tests and build on ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: corepack enable

      - run: corepack install

      - run: npx --yes dotenv-vault pull ci

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - run: yarn dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - run: yarn install --immutable --refresh-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: yarn nx-cloud record -- nx affected -t test build
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
