name: Copilot Setup

on:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:

jobs:
  # required name
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ./.github/workflows/setup-node.yml
        with:
          fetch-depth: 0
          set-nx-shas: true
      - name: install Node.js dependencies
        run: yarn
