name: Copilot Setup

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # required name
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0

      - name: fetch main branch
        if: ${{ github.event_name == 'pull_request' }}
        run: git fetch origin main:main

      - name: set SHAs for NX affected command
        uses: nrwl/nx-set-shas@v4

      - name: enable corepack and use it to install yarn
        run: |
          corepack enable
          corepack install

      - name: setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: yarn

      - name: install Node.js dependencies
        run: yarn
