name: Copilot Setup

on:
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:

jobs:
  # required name
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable && corepack install
      - uses: actions/setup-node@v5
        with:
          cache: yarn
          node-version: 24
      - run: yarn install
