name: Publish to NPM

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  publish:
    name: Publish npm packages
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-node.yml
        with:
          fetch-depth: 0

      - run: yarn install --frozen-lockfile

      - if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: yarn build

      - if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: yarn nx release publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
