name: Publish to NPM

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_CI }}

jobs:
  publish:
    name: Publish npm packages
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: corepack enable && corepack install

      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - run: yarn install --frozen-lockfile

      - if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: yarn build

      - if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: yarn nx release publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
