name: Node setup workflow

on:
  workflow_call:
    inputs:
      fetch-depth:
        required: false
        type: number
      set-nx-shas:
        default: true
        required: false
        type: boolean

permissions:
  actions: read
  contents: read

jobs:
  setup-node:
    name: Set up the Node.js environment
    runs-on: ubuntu-latest
    steps:
      - if: inputs.fetch-depth != null
        uses: actions/checkout@v5
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - if: inputs.fetch-depth == null
        uses: actions/checkout@v5
        with:
          filter: tree:0

      - if: ${{ inputs.set-nx-shas }}
        uses: nrwl/nx-set-shas@v4

      - run: corepack enable && corepack install

      - uses: actions/setup-node@v5
        with:
          cache: pnpm
          node-version: 24
